baseURL: http://example.org/
languageCode: en-us
title: My New Hugo Site
theme: github.com/theNewDynamic/gohugo-theme-ananke

SectionPagesMenu: "main"
Paginate: 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics: ""
enableRobotsTXT: true

params:
  text_color: ""
  author: ""
  favicon: ""
  site_logo: ""
  description: "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class: "bg-washed-red"
  recent_posts_number: 3